classdef AtlasForceTorque < SingletonCoordinateFrame
  
  methods
    function obj=AtlasForceTorque()

      coordinates = {'l_foot_fz','l_foot_tx','l_foot_ty',...
                'r_foot_fz','r_foot_tx','r_foot_ty',...
                'l_hand_fx','l_hand_fy','l_hand_fz',...
                'l_hand_tx','l_hand_ty','l_hand_tz',...
                'r_hand_fx','r_hand_fy','r_hand_fz',...
                'r_hand_tx','r_hand_ty','r_hand_tz'};

      obj = obj@SingletonCoordinateFrame('atlasFrames.AtlasForceTorque',length(coordinates),'f',coordinates);              
    end
  end
end
