# -*- python -*-
# This file contains rules for Bazel; see drake/doc/bazel.rst.

load("//tools:lint.bzl", "add_lint_tests")
load("//tools:install_data.bzl", "install_data")

package(default_visibility = ["//visibility:public"])

install_data()

add_lint_tests()
