function param_sets = getDefaultParams(r)
% NOTEST
  param_sets = struct('walking', valkyrieParams.Walking(r),...
                      'standing', valkyrieParams.Standing(r),...
                      'position_control', valkyrieParams.PositionControl(r),...
                      'recovery', valkyrieParams.Recovery(r),...
                      'manip',valkyrieParams.Manip(r));
end
