<?xml version="1.0"?>
<root xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="diameter" value="2.0"/>
  <sphere radius="${diameter/2}"/>
  <xacro:include filename="box.xml"/>
</root>
