# Per our style guide.
line-length = 80

# Per our oldest supported platform (currently Ubuntu 24.04 "Noble").
target-version = "py312"

[lint]

ignore = [
    # "Checks for unnecessary dict(), list() or tuple() calls that can be
    # rewritten as empty literals." If it were only empty ones that got dinged,
    # that would be fine, but it also rewrites `dict(a=1)` to `{"a": 1}` which
    # is sometimes less readable.
    "C408",
    # "Checks for str.format calls that can be replaced with f-strings."
    # In many cases this is a good idea, but not universally.
    "UP032",
    # TODO(jwnimmer-tri) These have been disabled as part of the ruff 0.16
    # upgrade. Either re-enable them or comment why we're keeping them off.
    "B004",
    "B005",
    "B006",
    "B008",
    "B015",
    "B017",
    "B018",
    "B023",
    "B026",
    "BLE001",
    "DTZ005",
    "EXE002",
    "FLY002",
    "FURB122",
    "FURB136",
    "ISC004",
    "LOG015",
    "PERF102",
    "PERF402",
    "PIE810",
    "PLC0206",
    "PLR0124",
    "PLR1722",
    "PLW1507",
    "PLW1510",
    "PYI041",
    "RUF007",
    "RUF009",
    "RUF012",
    "RUF013",
    "RUF015",
    "RUF051",
    "RUF059",
    "RUF100",
    "S102",
    "S110",
    "SIM101",
    "SIM102",
    "SIM103",
    "SIM115",
    "SIM117",
    "SIM118",
    "SIM201",
    "TRY002",
    "TRY004",
    "TRY201",
]

# Enable import sorting.
extend-select = ["I"]

[lint.isort]

# Interleave "straight" imports and "from" imports alphabetically.
force-sort-within-sections = true

# Group these separately from third-party imports.
known-first-party = [
    "doc",
    "drake",
    "examples",
    "pydrake",
    "tools",
]
