# Per our style guide.
line-length = 80

# Per our oldest supported platform (currently Ubuntu 24.04 "Noble").
target-version = "py312"

[per-file-target-version]

# This is run using Apple Python, so must retain its antiquated spellings.
"multibody/parsing/package_downloader.py" = "py39"

[lint]

ignore = [
    # "[Finds code] which can be replaced by next(iter(...))". Typical cases
    # are in unit tests, where the next(...) spelling is harder to read.
    "RUF015",
    # "Checks for noqa directives that are no longer applicable." We can't use
    # this because we have more linters than just `ruff`, and their noqa marks
    # confuse this check.
    "RUF100",
    # f-string checks for str.format calls that can be replaced with f-strings.
    # In many cases this is a good idea, but not universally.
    "UP032",
    # TODO(jwnimmer-tri) These have been disabled as part of the ruff 0.16
    # upgrade. Either re-enable them or comment why we're keeping them off.
    "B004",
    "B005",
    "B006",
    "B008",
    "B015",
    "B017",
    "B018",
    "B023",
    "B026",
    "BLE001",
    "C401",
    "C402",
    "C403",
    "C404",
    "C405",
    "C408",
    "C409",
    "C410",
    "C414",
    "C419",
    "DTZ005",
    "EXE002",
    "FLY002",
    "FURB122",
    "FURB136",
    "ISC004",
    "LOG015",
    "PERF102",
    "PERF402",
    "PIE810",
    "PLC0206",
    "PLR0124",
    "PLR1722",
    "PLW1507",
    "PLW1510",
    "PYI041",
    "RUF012",
    "S102",
    "S110",
    "SIM101",
    "SIM102",
    "SIM103",
    "SIM115",
    "SIM117",
    "SIM118",
    "SIM201",
    "TRY002",
    "TRY004",
    "TRY201",
]

# Enable import sorting.
extend-select = ["I"]

[lint.isort]

# Interleave "straight" imports and "from" imports alphabetically.
force-sort-within-sections = true

# Group these separately from third-party imports.
known-first-party = [
    "doc",
    "drake",
    "examples",
    "pydrake",
    "tools",
]
