# Per our style guide.
line-length = 80

# Per our oldest supported platform (currently Ubuntu 22.04 "Jammy").
target-version = "py310"

[lint]

# Enable import sorting.
extend-select = ["I"]

[lint.isort]

# Interleave "straight" imports and "from" imports alphabetically.
force-sort-within-sections = true

# Group these separately from third-party imports.
known-first-party = [
    "doc",
    "drake",
    "examples",
    "pydrake",
    "tools",
]
