#!/bin/bash

###########################
# Colours
###########################

# check if stdout is a terminal...
if test -t 1; then
 
    # see if it supports colors...
    ncolors=$(tput colors)
 
    if test -n "$ncolors" && test $ncolors -ge 8; then
        BOLD="$(tput bold)"
        UNDERLINE="$(tput smul)"
        STANDOUT="$(tput smso)"
        RESET="$(tput sgr0)"
        BLACK="$(tput setaf 0)"
        RED="$(tput setaf 1)"
        GREEN="$(tput setaf 2)"
        YELLOW="$(tput setaf 3)"
        BLUE="$(tput setaf 4)"
        MAGENTA="$(tput setaf 5)"
        CYAN="$(tput setaf 6)"
        WHITE="$(tput setaf 7)"
    fi
fi

###########################
# Find
###########################

DOXYGEN_EXECUTABLE=`which doxygen`

if [ $? -ne 0 ]; then
  echo -e "${RED}ERROR : doxygen executable not found, aborting.${RESET}"
  exit 1
fi

SPHINX_EXECUTABLE=`which sphinx-build`

if [ $? -ne 0 ]; then
  echo -e "${RED}ERROR : sphinx-build executable not found, aborting.${RESET}"
  exit 1
fi


