#!/bin/bash

# This shell script is used to complete the manual steps at the end of the
# release process.

set -euo pipefail

readonly usage="Usage: $0 {{ source version x.y.z }}"

if [[ "$#" -lt 1 ]]; then
  echo "${usage}" >&2
  exit 1
fi

readonly source_version=$1

shift 1;

if ! tty -s; then
  echo 'ERROR: tty was NOT detected. ' \
    'This script may need various login credentials' \
    'to be entered interactively.'  >&2
  exit 2
fi

if ! command -v aptly &>/dev/null; then
  echo 'ERROR: aptly(1) was NOT found. Fix with ' \
    'apt-get install aptly or brew install aptly.' >&2
  exit 3
fi

if ! command -v aws &>/dev/null; then
  echo 'ERROR: aws(1) was NOT found. Fix with ' \
    'apt-get install awscli or brew install awscli.' >&2
  exit 4
fi

# curl is always available on macOS.
if ! command -v curl &>/dev/null; then
  echo 'ERROR: curl(1) was NOT found. Fix with apt-get install curl.' >&2
  exit 5
fi

if ! command -v gpg &>/dev/null; then
  echo 'ERROR: gpg(1) was NOT found. Fix with ' \
    'apt-get install gnupg or brew install gnupg.' >&2
  exit 6
fi

# Sanity check that the release for the source version exists and has been
# published.
readonly drake_gh_api="https://api.github.com/repos/RobotLocomotion/drake"
readonly release_api_url="${drak_gh_api}/releases/tags/v${source_version}"
if ! curl --fail --head --location --output /dev/null \
    "${release_api_url}"; then
  echo "ERROR: GitHub release v${source_version} does NOT exist." >&2
  exit 8
fi

platforms=( jammy noble )

readonly gpg_key="$(
  curl --fail https://drake-apt.csail.mit.edu/drake.asc | \
  gpg --with-colons --show-keys --fingerprint | \
  grep -m1 -E '^fpr:' | cut -c 4- | tr -d :)"

if ! [[ "${gpg_key}" =~ ^[a-fA-F0-9]{40}$ ]]; then
  echo 'ERROR: gpg_key value expected to be a length 40 ' \
    'hexadecimal string.' >&2
  exit 1
fi

if ! gpg --list-secret-keys "${gpg_key}" &>/dev/null; then
  echo "ERROR: GPG secret key ${gpg_key} does NOT exist." >&2
  exit 10
fi

if [ ! -s "${HOME}/.aptly.conf" ]; then
  echo "ERROR: aptly is NOT configured." >&2
  exit 11
fi

readonly temp_dir="$(mktemp -u)"

mkdir -p "${temp_dir}"
pushd "${temp_dir}"

set -x

# Download the current version of the aptly database from S3.
aws s3 sync --delete s3://drake-infrastructure/aptly/.aptly "${HOME}/.aptly"

for platform in "${platforms[@]}"; do
  mkdir -p "${platform}"
  pushd "${platform}"

  repo="drake-${platform}"
  snapshot="${repo}-${source_version}"

  # Create the repository if it doesn't already exist.
  if ! aptly repo show "${repo}" &>/dev/null; then
    read -p "Local repo ${repo} doesn't exist. Create it? (y/n)" -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
      aptly repo create -distribution="${platform}" "${repo}"
    else
      echo "Aborting."
      exit 1
    fi
  fi

  remote_filename="drake-dev_${source_version}-1_amd64-${platform}.deb"
  local_filename="drake-dev_${source_version}-1_amd64.deb"

  curl --fail --location -o "${local_filename}" \
    "https://drake-packages.csail.mit.edu/drake/release/${remote_filename}"

  # Add the Debian package to the aptly database.
  aptly repo add "${repo}" "${local_filename}"
  aptly snapshot create "${snapshot}" from repo "${repo}"

  # Create a folder in S3 for the destination if it doesn't exist already.
  if ! aws s3api head-object --bucket drake-apt \
      --key "${platform}/" &>/dev/null; then
    echo "Folder ${platform}/ in S3 drake-apt bucket doesn't exist."
    read -p "Create it? (y/n)" -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
      aws s3api put-object --bucket drake-apt --key "${platform}/" \
        --content-length 0
    else
      echo "Aborting."
      exit 1
    fi
  fi

  # Publish the new apt repository to S3.
  if aptly publish list -raw | awk '{print $2}' | grep -qx "${platform}"; then
    # If it already exists, 'switch'.
    aptly publish switch -gpg-key="${gpg_key: -8}" "${platform}" \
      "s3:drake-apt.csail.mit.edu/${platform}:" "${snapshot}"
  else
    # Otherwise, 'snapshot'.
    aptly publish snapshot -gpg-key="${gpg_key: -8}" \
      -distribution="${platform}" \
      "${snapshot}" \
      "s3:drake-apt.csail.mit.edu/${platform}:"
  fi

  # Invalidate the cached apt repository.
  aws cloudfront create-invalidation --distribution-id E2RAGJYS5GNIOS \
    --paths "/${platform}/dists/${platform}/*"

  popd
done

# Upload the new version of the aptly database to S3.
aws s3 sync --delete --exclude .DS_Store "${HOME}/.aptly" \
  s3://drake-infrastructure/aptly/.aptly

set +x

popd

# Remove the downloaded files on success.
rm -rf "${temp_dir}"
