function A_blockwise_transpose = blockwiseTranspose(A,block_size)
  elementwise_size_A = size(A);
  blockwise_size_A = elementwise_size_A./block_size;
  if ~all(mod(blockwise_size_A,1)==0)
    error(['The dimensions of A must be integer multiples of the ' ...
            'dimensions of the block']);
  end
  A_blockwise_transpose = ...
    reshape( ...
      permute( ...
        reshape( ...
          A,[block_size(1),blockwise_size_A(1),block_size(2),blockwise_size_A(2)] ...
        ), ...
        [1,4,3,2] ...
      ), ...
      block_size.*fliplr(blockwise_size_A) ...
    );
end
