kinematic_tree_metadata:
  body_names:
    feet:
      r: &R_FOOT_NAME "rightFoot"
      l: &L_FOOT_NAME "leftFoot"
    pelvis: &PELVIS_NAME pelvis
    hands:
      r: &R_HAND_NAME rightPalm
      l: &L_HAND_NAME leftPalm

  joint_group_names:
    legs:
      r: [rightHipYaw, rightHipRoll, rightHipPitch, rightKneePitch, rightAnklePitch, rightAnkleRoll]
      l: [leftHipYaw, leftHipRoll, leftHipPitch, leftKneePitch, leftAnklePitch, leftAnkleRoll]
    knees:
      r: rightKneePitch
      l: leftKneePitch
    ankles:
      r: [rightAnklePitch, leftAnkleRoll]
      l: [leftAnklePitch, rightAnkleRoll]
    arms:
      r: [rightShoulderPitch, rightShoulderRoll, rightShoulderYaw, rightElbowPitch, rightForearmYaw, rightWristRoll, rightWristPitch]
      l: [leftShoulderPitch, leftShoulderRoll, leftShoulderYaw, leftElbowPitch, leftForearmYaw, leftWristRoll, leftWristPitch]

    neck: [lowerNeckPitch]
    back_bkz: torsoYaw
    back_bky: torsoPitch

joint_names:
  - torsoYaw
  - torsoPitch
  - torsoRoll
  - lowerNeckPitch
  - leftHipYaw
  - leftHipRoll
  - leftHipPitch
  - leftKneePitch
  - leftAnklePitch
  - leftAnkleRoll
  - rightHipYaw
  - rightHipRoll
  - rightHipPitch
  - rightKneePitch
  - rightAnklePitch
  - rightAnkleRoll
  - leftShoulderPitch
  - leftShoulderRoll
  - leftShoulderYaw
  - leftElbowPitch
  - leftForearm
  - leftWristRoll
  - leftWristPitch
  - rightShoulderPitch
  - rightShoulderRoll
  - rightShoulderYaw
  - rightElbowPitch
  - rightForearm
  - rightWristRoll
  - rightWristPitch




qp_controller_params:
  DEFAULT:
    body_specific:
      DEFAULT:
        Kp: {x: 12, y: 12, z: 12, wx: 12, wy: 12, wz: 12}
        damping_ratio: 0.7
        accel_bounds:
          min: {x: -100, y: -100, z: -100, wx: -50, wy: -50, wz: -50}
          max: {x: 100, y: 100, z: 100, wx: 50, wy: 50, wz: 50}
        weight: 0.0
      *PELVIS_NAME :
        Kp: {x: 150, y: 150, z: 150, wx: 200, wy: 200, wz: 200}
        weight: 0.01
        damping_ratio: 0.6
      *R_FOOT_NAME :
        weight: 0.01
      *L_FOOT_NAME :
        weight: 0.01
    position_specific:
      DEFAULT:
        Kp: 150
        damping_ratio: 0.6
        w_qdd: 0.001
        integrator:
          gain: 0
          clamp: 0
        qdd_bounds:
          min: -100
          max: 100
        joint_soft_limits:
          enabled: false
          lb: -.inf
          ub: .inf
          kp: 150
          damping_ratio: 0.6
          weight: 1e-5
          disable_when_body_in_support: ""
          k_logistic: 20
      base_x:
        w_qdd: 0
      base_y:
        w_qdd: 0
      base_z:
        w_qdd: 0
      base_roll:
        w_qdd: 0
      base_pitch:
        w_qdd: 0
      base_yaw:
        w_qdd: 0
      rightKneePitch:
        joint_soft_limits:
          enabled: true
          lb: 0.5
          disable_when_body_in_support: *R_FOOT_NAME
      leftKneePitch:
        joint_soft_limits:
          enabled: true
          lb: 0.5
          disable_when_body_in_support: *L_FOOT_NAME
      torsoRoll:
        w_qdd: 0.1
        Kp: 50
    vref_integrator:
      zero_ankles_on_contact: false
      eta: 0.001
      delta_max: 10
    integrator:
      eta: 0.0
    W_kdot: 0
    Kp_ang: 0
    w_slack: 0.05
    slack_limit: 100
    w_grf: 0
    Kp_accel: 1
    contact_threshold: 0.002
    min_knee_angle: 0.7
    center_of_mass_observer:
      enabled: false
      l_zmp: 10
      l_com: 6.324555320336759 # 2 * sqrt(l_zmp)
    input_specific:
      DEFAULT:
        hardware:
          joint_is_force_controlled: true
          joint_is_position_controlled: false
          k_f_p: 0
          k_q_p: 0
          k_q_i: 0
          k_qd_p: 0
          ff_qd: 0
          ff_f_d: 0
          ff_const: 0
          ff_qd_d: 0

  base: # automatically inherits from the default =
  standing:
  manip:
    body_specific:
      *L_HAND_NAME :
        weight: 0.001
      *R_HAND_NAME :
        weight: 0.001

  walking:
    body_specific:
      DEFAULT:
        weight: 0.001
      *PELVIS_NAME :
        Kp: {x: 0, y: 0, z: 150, wx: 200, wy: 200, wz: 200}
        weight: 0.075
      *R_FOOT_NAME :
        Kp: {x: 100, y: 100, z: 100, wx: 150, wy: 150, wz: 150}
        damping_ratio: 0.5
        weight: 0.001
      *L_FOOT_NAME :
        Kp: {x: 100, y: 100, z: 100, wx: 150, wy: 150, wz: 150}
        damping_ratio: 0.5
        weight: 0.001
    position_specific:
      DEFAULT:
        w_qdd: 0
        damping_ratio: 0.5
      rightHipYaw: {w_qdd: 1e-6, damping_ratio: 0.5}
      rightHipRoll: {w_qdd: 1e-6, damping_ratio: 0.5}
      rightHipPitch: {w_qdd: 1e-6, damping_ratio: 0.5}
      rightKneePitch: {w_qdd: 1e-6, damping_ratio: 0.5}
      rightAnklePitch: {w_qdd: 1e-6, damping_ratio: 0.5}
      rightAnkleRoll: {w_qdd: 1e-6, damping_ratio: 0.5}
      leftHipYaw: {w_qdd: 1e-6, damping_ratio: 0.5}
      leftHipRoll: {w_qdd: 1e-6, damping_ratio: 0.5}
      leftHipPitch: {w_qdd: 1e-6, damping_ratio: 0.5}
      leftKneePitch: {w_qdd: 1e-6, damping_ratio: 0.5}
      leftAnklePitch: {w_qdd: 1e-6, damping_ratio: 0.5}
      leftAnkleRoll: {w_qdd: 1e-6, damping_ratio: 0.5}
      torsoRoll:
        w_qdd: 0.1
        Kp: 50
        damping_ratio: 0.5
      torsoPitch:
        w_qdd: 1e-4
        damping_ratio: 0.5
      torsoYaw:
        w_qdd: 1e-4
        damping_ratio: 0.5
    contact_threshold: 0.001
    Kp_accel: 0

  recovery:
    body_specific:
      DEFAULT:
        weight: 0.001
      *PELVIS_NAME :
        Kp: {x: 0, y: 0, z: 150, wx: 200, wy: 200, wz: 200}
        weight: 0.075
      *R_FOOT_NAME :
        Kp: {x: 1000, y: 1000, z: 1000, wx: 1500, wy: 1500, wz: 1500}
        damping_ratio: 0.5
        weight: 0.001
      *L_FOOT_NAME :
        Kp: {x: 1000, y: 1000, z: 1000, wx: 1500, wy: 1500, wz: 1500}
        damping_ratio: 0.5
        weight: 0.001
    position_specific:
      DEFAULT:
        w_qdd: 0
        damping_ratio: 0.5
      rightHipYaw: {w_qdd: 1e-6, damping_ratio: 0.5}
      rightHipRoll: {w_qdd: 1e-6, damping_ratio: 0.5}
      rightHipPitch: {w_qdd: 1e-6, damping_ratio: 0.5}
      rightKneePitch: {w_qdd: 1e-6, damping_ratio: 0.5}
      rightAnklePitch: {w_qdd: 1e-6, damping_ratio: 0.5}
      rightAnkleRoll: {w_qdd: 1e-6, damping_ratio: 0.5}
      leftHipYaw: {w_qdd: 1e-6, damping_ratio: 0.5}
      leftHipRoll: {w_qdd: 1e-6, damping_ratio: 0.5}
      leftHipPitch: {w_qdd: 1e-6, damping_ratio: 0.5}
      leftKneePitch: {w_qdd: 1e-6, damping_ratio: 0.5}
      leftAnklePitch: {w_qdd: 1e-6, damping_ratio: 0.5}
      leftAnkleRoll: {w_qdd: 1e-6, damping_ratio: 0.5}
      torsoRoll:
        w_qdd: 0.1
        Kp: 50
        damping_ratio: 0.5
      torsoPitch:
        w_qdd: 1e-4
        damping_ratio: 0.5
      torsoYaw:
        w_qdd: 1e-4
        damping_ratio: 0.5
    contact_threshold: 0.001
    Kp_accel: 0

######################## position control #########################
  position_control:
    position_specific:
      torsoRoll:
        integrator:
          gain: 0.3
          clamp: 0.2
      torsoPitch:
        integrator:
          gain: 0.3
          clamp: 0.2
      torsoYaw:
        integrator:
          gain: 0.3
          clamp: 0.2
      leftHipRoll:
        integrator:
          gain: 0.3
          clamp: 0.1
      leftHipPitch:
        integrator:
          gain: 0.3
          clamp: 0.1
      leftHipYaw:
        integrator:
          gain: 0.3
          clamp: 0.1
      leftKneePitch:
        integrator:
          gain: 0.3
          clamp: 0.1
      leftAnkleRoll:
        integrator:
          gain: 0.3
          clamp: 0.1
      leftAnklePitch:
        integrator:
          gain: 0.3
          clamp: 0.1
      rightHipRoll:
        integrator:
          gain: 0.3
          clamp: 0.1
      rightHipPitch:
        integrator:
          gain: 0.3
          clamp: 0.1
      rightHipYaw:
        integrator:
          gain: 0.3
          clamp: 0.1
      rightKneePitch:
        integrator:
          gain: 0.3
          clamp: 0.1
      rightAnkleRoll:
        integrator:
          gain: 0.3
          clamp: 0.1
      rightAnklePitch:
        integrator:
          gain: 0.3
          clamp: 0.1

######################## bracing ##################################
  bracing:
    position_specific:
      DEFAULT:
        Kp: 170
        damping_ratio: 1.1
        w_qdd: 1
        integrator:
          gain: 0
          clamp: 0
      base_x:
        Kp: 0
        w_qdd: 1
      base_y:
        Kp: 0
        w_qdd: 1
      base_z:
        Kp: 0
        w_qdd: 1
      base_roll:
        Kp: 0
        w_qdd: 1
      base_pitch:
        Kp: 0
        w_qdd: 1
      base_yaw:
        Kp: 0
        w_qdd: 1
      torsoRoll:
        Kp: 170
        w_qdd: 1
    body_specific:
      DEFAULT:
        Kp: {x: 0, y: 0, z: 0, wx: 0, wy: 0, wz: 0}
        damping_ratio: 0