set(CMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY ON)
set(CMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY ON)

find_package(drake CONFIG REQUIRED)
find_package(Eigen3 3.3.3 CONFIG REQUIRED)
find_package(Matlab 9 MODULE REQUIRED COMPONENTS
  MAIN_PROGRAM MEX_COMPILER MX_LIBRARY
)
find_package(Protobuf 2.6 MODULE REQUIRED)
