#!/usr/bin/env python3

import os
import sys


def main():
    print("""
Drake's installed optitrack_client script is deprecated and will be removed
from future releases on or after 2023-11-01. As a replacement, use the wheel
packages provided by https://github.com/RobotLocomotion/optitrack-driver.
""")

    prefix = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    sys.path.insert(0, os.path.join(
        prefix, 'lib',
        'python{}.{}'.format(sys.version_info.major, sys.version_info.minor),
        'site-packages'))

    import optitrack.optitrack_client

    optitrack.optitrack_client.main()


if __name__ == '__main__':
    main()
