function runValkyrieFastWalking()
path_handle = addpathTemporary(fullfile(getDrakePath(), 'examples', 'Valkyrie'));
runValkyrieWalking([], struct('navgoal', [2.0;0;0;0;0;0],...
                                'max_forward_step', 0.75,...
                                'nom_step_width', 0.2,...
                                'step_speed', 3.0,...
                                'drake_min_hold_time', 0.01,...
                                'rms_com_tolerance', 0.03));
end