name: Post-Release Actions
title: Post-release actions for release <version>
description:
  Create a tracking issue for Docker image tagging, S3 upload, and Apt
  repository updates for a new Drake release.
labels: ["type: release"]
assignees: BetsyMcPhail
body:
  - type: input
    id: version
    attributes:
      label: Release Version
      description:
        "Enter the release version number WITHOUT the 'v' prefix (e.g.,
        1.N.0)"
      placeholder: "1.N.0"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Post-Release Documentation
      value: |

        This issue tracks the required post-release actions that need to be completed after the Drake release has been published to GitHub.

        For detailed instructions, refer to the [Docker / Apt / S3 Release Process](https://github.com/RobotLocomotion/drake/blob/master/tools/release_engineering/dev/README.md).

        To see the build artifacts for the latest Drake release, visit the [Drake GitHub Releases page](https://github.com/RobotLocomotion/drake/releases/latest).
  - type: checkboxes
    id: tasks
    attributes:
      label: Post-Release Tasks
      description:
        "These two steps must be completed in order. Check each box after
        completion."
      options:
        - label: >
            Run script to push Docker images, mirror the artifacts to S3, and
            push the source archive to GitHub
          required: false
        - label: "Run script for Apt repository updates"
          required: false
