# This file is automatically generated by upgrade.py.

ARCHIVES = [
    dict(
        name = "rust_darwin_aarch64__aarch64-apple-darwin__stable",
        build_file = Label("@drake//tools/workspace/rust_toolchain:lock/details/BUILD.rust_darwin_aarch64__aarch64-apple-darwin__stable.bazel"),
        downloads = "[]",
    ),
    dict(
        name = "rust_darwin_aarch64__aarch64-apple-darwin__stable_tools",
        build_file = Label("@drake//tools/workspace/rust_toolchain:lock/details/BUILD.rust_darwin_aarch64__aarch64-apple-darwin__stable_tools.bazel"),
        downloads = json.encode(
            [
                {
                    "sha256": "7f6e7e0800711aded0a35349bd2e1efcb1eaf8c2f080693a69f252195290c888",
                    "stripPrefix": "rustc-1.78.0-aarch64-apple-darwin/rustc",
                    "url": [
                        "https://static.rust-lang.org/dist/rustc-1.78.0-aarch64-apple-darwin.tar.xz",
                    ],
                },
                {
                    "sha256": "6ed693740cd5e1546ff3e0d92279742e25fd3d8fcf566d0b3d12a1b3a3a39237",
                    "stripPrefix": "clippy-1.78.0-aarch64-apple-darwin/clippy-preview",
                    "url": [
                        "https://static.rust-lang.org/dist/clippy-1.78.0-aarch64-apple-darwin.tar.xz",
                    ],
                },
                {
                    "sha256": "76b9a39eea441b31c6b26cc58ebff7095a64bc60788254c2525e752a1149688d",
                    "stripPrefix": "cargo-1.78.0-aarch64-apple-darwin/cargo",
                    "url": [
                        "https://static.rust-lang.org/dist/cargo-1.78.0-aarch64-apple-darwin.tar.xz",
                    ],
                },
                {
                    "sha256": "cf87e321ffa214765bcdd7173101f8e8ee6c2a6c42e072e5b5308da687b98b26",
                    "stripPrefix": "rustfmt-1.78.0-aarch64-apple-darwin/rustfmt-preview",
                    "url": [
                        "https://static.rust-lang.org/dist/rustfmt-1.78.0-aarch64-apple-darwin.tar.xz",
                    ],
                },
                {
                    "sha256": "491a52cddfb2121a2f5a450d0317e56150259d27ac47d7cb41471c3fe18d8e79",
                    "stripPrefix": "llvm-tools-1.78.0-aarch64-apple-darwin/llvm-tools-preview",
                    "url": [
                        "https://static.rust-lang.org/dist/llvm-tools-1.78.0-aarch64-apple-darwin.tar.xz",
                    ],
                },
                {
                    "sha256": "4ab399e983e6f4b21687010842774e5b7c679641360b0b85ac9b27a426bec4c1",
                    "stripPrefix": "rust-std-1.78.0-aarch64-apple-darwin/rust-std-aarch64-apple-darwin",
                    "url": [
                        "https://static.rust-lang.org/dist/rust-std-1.78.0-aarch64-apple-darwin.tar.xz",
                    ],
                },
            ],
        ),
    ),
    dict(
        name = "rust_darwin_x86_64__x86_64-apple-darwin__stable",
        build_file = Label("@drake//tools/workspace/rust_toolchain:lock/details/BUILD.rust_darwin_x86_64__x86_64-apple-darwin__stable.bazel"),
        downloads = "[]",
    ),
    dict(
        name = "rust_darwin_x86_64__x86_64-apple-darwin__stable_tools",
        build_file = Label("@drake//tools/workspace/rust_toolchain:lock/details/BUILD.rust_darwin_x86_64__x86_64-apple-darwin__stable_tools.bazel"),
        downloads = json.encode(
            [
                {
                    "sha256": "6640eff5f62ed961a8bf1c0b148daf848f94c46ad3bda19992428173d9830502",
                    "stripPrefix": "rustc-1.78.0-x86_64-apple-darwin/rustc",
                    "url": [
                        "https://static.rust-lang.org/dist/rustc-1.78.0-x86_64-apple-darwin.tar.xz",
                    ],
                },
                {
                    "sha256": "cdbed0e1b31d035f1a2d5869aa48e6585c544a50c9345d2e8fbdee860dcdc580",
                    "stripPrefix": "clippy-1.78.0-x86_64-apple-darwin/clippy-preview",
                    "url": [
                        "https://static.rust-lang.org/dist/clippy-1.78.0-x86_64-apple-darwin.tar.xz",
                    ],
                },
                {
                    "sha256": "4d4078695265c8489ee5dfefd87d26caa1755a4f46f56f6f07f2b7b7292416c8",
                    "stripPrefix": "cargo-1.78.0-x86_64-apple-darwin/cargo",
                    "url": [
                        "https://static.rust-lang.org/dist/cargo-1.78.0-x86_64-apple-darwin.tar.xz",
                    ],
                },
                {
                    "sha256": "9b8f2bd5e3e56c5141d8a0a261fc4e107a387f33deb27cb7382c1703350f32cc",
                    "stripPrefix": "rustfmt-1.78.0-x86_64-apple-darwin/rustfmt-preview",
                    "url": [
                        "https://static.rust-lang.org/dist/rustfmt-1.78.0-x86_64-apple-darwin.tar.xz",
                    ],
                },
                {
                    "sha256": "b35548d2b9714bdcd2c9df278ec6dd0923e0741f7a3d8fd96e16cd96a49932d1",
                    "stripPrefix": "llvm-tools-1.78.0-x86_64-apple-darwin/llvm-tools-preview",
                    "url": [
                        "https://static.rust-lang.org/dist/llvm-tools-1.78.0-x86_64-apple-darwin.tar.xz",
                    ],
                },
                {
                    "sha256": "dcf0777625819463a7fb648fc8a232a44110886e4d42084f3f9bddd2284460c4",
                    "stripPrefix": "rust-std-1.78.0-x86_64-apple-darwin/rust-std-x86_64-apple-darwin",
                    "url": [
                        "https://static.rust-lang.org/dist/rust-std-1.78.0-x86_64-apple-darwin.tar.xz",
                    ],
                },
            ],
        ),
    ),
    dict(
        name = "rust_linux_aarch64__aarch64-unknown-linux-gnu__stable",
        build_file = Label("@drake//tools/workspace/rust_toolchain:lock/details/BUILD.rust_linux_aarch64__aarch64-unknown-linux-gnu__stable.bazel"),
        downloads = "[]",
    ),
    dict(
        name = "rust_linux_aarch64__aarch64-unknown-linux-gnu__stable_tools",
        build_file = Label("@drake//tools/workspace/rust_toolchain:lock/details/BUILD.rust_linux_aarch64__aarch64-unknown-linux-gnu__stable_tools.bazel"),
        downloads = json.encode(
            [
                {
                    "sha256": "e0450bef5537e6b0bb82872e9f837c3b3f6397cc8eba6f53211481c82426e1ce",
                    "stripPrefix": "rustc-1.78.0-aarch64-unknown-linux-gnu/rustc",
                    "url": [
                        "https://static.rust-lang.org/dist/rustc-1.78.0-aarch64-unknown-linux-gnu.tar.xz",
                    ],
                },
                {
                    "sha256": "086367aa83ea8c30ce41fb6c097ae6ebdc92363fb1ce8ee9f01d44cafa625f61",
                    "stripPrefix": "clippy-1.78.0-aarch64-unknown-linux-gnu/clippy-preview",
                    "url": [
                        "https://static.rust-lang.org/dist/clippy-1.78.0-aarch64-unknown-linux-gnu.tar.xz",
                    ],
                },
                {
                    "sha256": "5173f84a07d4cc6b19f27eda7464999c5886232ce8e54bf61b06617635d43fb9",
                    "stripPrefix": "cargo-1.78.0-aarch64-unknown-linux-gnu/cargo",
                    "url": [
                        "https://static.rust-lang.org/dist/cargo-1.78.0-aarch64-unknown-linux-gnu.tar.xz",
                    ],
                },
                {
                    "sha256": "302420a3069abaf10a3b3df5b3278a0c5031be033f71b002544f223898cd2740",
                    "stripPrefix": "rustfmt-1.78.0-aarch64-unknown-linux-gnu/rustfmt-preview",
                    "url": [
                        "https://static.rust-lang.org/dist/rustfmt-1.78.0-aarch64-unknown-linux-gnu.tar.xz",
                    ],
                },
                {
                    "sha256": "9b27d94ef96b23647168345e5a5b5d36b4aa9a7760f2265be4295814851599bd",
                    "stripPrefix": "llvm-tools-1.78.0-aarch64-unknown-linux-gnu/llvm-tools-preview",
                    "url": [
                        "https://static.rust-lang.org/dist/llvm-tools-1.78.0-aarch64-unknown-linux-gnu.tar.xz",
                    ],
                },
                {
                    "sha256": "66cf114dcd8056a596bf169f824ff95ff1837bc065daaafdbcaa02ce92903304",
                    "stripPrefix": "rust-std-1.78.0-aarch64-unknown-linux-gnu/rust-std-aarch64-unknown-linux-gnu",
                    "url": [
                        "https://static.rust-lang.org/dist/rust-std-1.78.0-aarch64-unknown-linux-gnu.tar.xz",
                    ],
                },
            ],
        ),
    ),
    dict(
        name = "rust_linux_x86_64__x86_64-unknown-linux-gnu__stable",
        build_file = Label("@drake//tools/workspace/rust_toolchain:lock/details/BUILD.rust_linux_x86_64__x86_64-unknown-linux-gnu__stable.bazel"),
        downloads = "[]",
    ),
    dict(
        name = "rust_linux_x86_64__x86_64-unknown-linux-gnu__stable_tools",
        build_file = Label("@drake//tools/workspace/rust_toolchain:lock/details/BUILD.rust_linux_x86_64__x86_64-unknown-linux-gnu__stable_tools.bazel"),
        downloads = json.encode(
            [
                {
                    "sha256": "3994971e5923716d54e4b574ce238f04c4e20cda03990670f7cc3f87d36e5499",
                    "stripPrefix": "rustc-1.78.0-x86_64-unknown-linux-gnu/rustc",
                    "url": [
                        "https://static.rust-lang.org/dist/rustc-1.78.0-x86_64-unknown-linux-gnu.tar.xz",
                    ],
                },
                {
                    "sha256": "b15184ba6078dd7976f06239a258313a96de2677b37e4c560779cf7f261c3ee5",
                    "stripPrefix": "clippy-1.78.0-x86_64-unknown-linux-gnu/clippy-preview",
                    "url": [
                        "https://static.rust-lang.org/dist/clippy-1.78.0-x86_64-unknown-linux-gnu.tar.xz",
                    ],
                },
                {
                    "sha256": "f8aacf7a101eb10dc000b8bf26de90a9d0ce678d02ccf70430ed20dd31ecec6b",
                    "stripPrefix": "cargo-1.78.0-x86_64-unknown-linux-gnu/cargo",
                    "url": [
                        "https://static.rust-lang.org/dist/cargo-1.78.0-x86_64-unknown-linux-gnu.tar.xz",
                    ],
                },
                {
                    "sha256": "c9b9a240602b568eafa04905b7f731eccd7079d701b72dc9f23d8c7395ef9a92",
                    "stripPrefix": "rustfmt-1.78.0-x86_64-unknown-linux-gnu/rustfmt-preview",
                    "url": [
                        "https://static.rust-lang.org/dist/rustfmt-1.78.0-x86_64-unknown-linux-gnu.tar.xz",
                    ],
                },
                {
                    "sha256": "cc3719fd95adf19a2af79d1908afc47779646a8c2f4c4a473181bec90695cfdc",
                    "stripPrefix": "llvm-tools-1.78.0-x86_64-unknown-linux-gnu/llvm-tools-preview",
                    "url": [
                        "https://static.rust-lang.org/dist/llvm-tools-1.78.0-x86_64-unknown-linux-gnu.tar.xz",
                    ],
                },
                {
                    "sha256": "95aece42a336f237c5bac5c5d9aca051b7f0bd3e6a64fb3c5828e6d0d3af2e8c",
                    "stripPrefix": "rust-std-1.78.0-x86_64-unknown-linux-gnu/rust-std-x86_64-unknown-linux-gnu",
                    "url": [
                        "https://static.rust-lang.org/dist/rust-std-1.78.0-x86_64-unknown-linux-gnu.tar.xz",
                    ],
                },
            ],
        ),
    ),
]
