# -*- python -*-
# This file contains rules for Bazel; see drake/doc/bazel.rst.

load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "side",
    srcs = ["Side.cpp"],
    hdrs = ["Side.h"],
    linkstatic = 1,
    deps = [],
)

cpplint()
