load("//tools/install:install.bzl", "install")
load("//tools/lint:lint.bzl", "add_lint_tests")
load("//tools/skylark:drake_py.bzl", "drake_py_binary")

exports_files(glob(["lock/**"]))

install(
    name = "install",
    visibility = ["//visibility:public"],
    deps = ["@crate_licenses//:install"],
)

drake_py_binary(
    name = "upgrade",
    srcs = ["upgrade.py"],
    data = ["@rules_rust//tools/upstream_wrapper:cargo"],
    env = {
        "DRAKE_CARGO_RLOCATIONPATH": "$(rlocationpath @rules_rust//tools/upstream_wrapper:cargo)",
    },
    deps = ["@rules_python//python/runfiles"],
)

add_lint_tests(
    python_lint_exclude = [":upgrade.py"],
    python_lint_extra_srcs = ["upgrade.py"],
)
