# -*- bazel -*-

# This is the BUILD file for our @crate_licenses module extension.
# Refer to extensions.bzl for how it gets used.

load("@drake//tools/install:install.bzl", "install")
load(
    "@drake//tools/workspace/crate_universe:defs.bzl",
    "install_crate_license",
)
load(":lock/repo_names.bzl", "REPO_NAMES")

exports_files([
    "Cargo.lock",
    "Cargo.toml",
    "src/lib.rs",
])

[
    install_crate_license(
        name = "install_{}".format(name),
        crate = "@crates//:{}".format(name),
        doc_dest = "share/doc/crate_universe/{}".format(name),
        tags = ["install"],
    )
    for name in REPO_NAMES
]

install(
    name = "install",
    visibility = ["@drake//tools/workspace/crate_universe:__pkg__"],
    deps = [
        "install_{}".format(name)
        for name in REPO_NAMES
    ],
)
