function param_sets = getDefaults(r)
% NOTEST
  typecheck(r, 'Atlas');
  param_sets = struct('walking', atlasParams.Walking(r),...
                      'standing', atlasParams.Standing(r),...
                      'kinematic', atlasParams.Kinematic(r),...
                      'recovery', atlasParams.Recovery(r));
end
