# -*- bazel -*-

load(
    "@drake//third_party:com_github_bazelbuild_rules_cc/whole_archive.bzl",
    "cc_whole_archive_library",
)
load("@drake//tools/install:install.bzl", "install")
load("@drake//tools/skylark:cc.bzl", "cc_binary", "cc_library")

licenses(["notice"])  # BSD-3-Clause

package(default_visibility = ["//visibility:private"])

# XXX porting The BCR module for this has a better build rule.  We should
# probably mimic what it does (or just use it directly), depending on how
# we eventually decide that nanobind needs to be linked / released.

USE_SHARED_LIBRARY = True

cc_library(
    name = "hdrs",
    hdrs = glob([
        "include/nanobind/*.h",
        "include/nanobind/intrusive/*.h",
        "include/nanobind/stl/*.h",
        "include/nanobind/stl/detail/*.h",
    ]),
    defines = ["NB_SHARED"] if USE_SHARED_LIBRARY else ["NB_STATIC"],
    strip_include_prefix = "include",
    deps = [
        "@drake//tools/workspace/python:cc_headers",
    ],
)

cc_library(
    name = "srcs",
    srcs = glob(
        [
            "src/*.cpp",
            "src/*.h",
        ],
        exclude = ["src/nb_combined.cpp"],
    ),
    implementation_deps = [
        "@robin-map",
    ],
    strip_include_prefix = "include",
    deps = [
        ":hdrs",
    ],
)

cc_whole_archive_library(
    name = "whole_archive",
    deps = [":srcs"],
)

config_setting(
    name = "linux",
    constraint_values = ["@platforms//os:linux"],
)

cc_binary(
    name = "libdrake_nanobind.so",
    linkopts = select({
        ":linux": ["-Wl,-soname,libdrake_nanobind.so"],
        "//conditions:default": [],
    }),
    linkshared = True,
    deps = [":whole_archive"],
)

cc_library(
    name = "nanobind",
    srcs = [":libdrake_nanobind.so"] if USE_SHARED_LIBRARY else [],
    implementation_deps = [
        "@drake//tools/workspace/python:cc_libs",
    ] if USE_SHARED_LIBRARY else [
        ":srcs",
        "@drake//tools/workspace/python:cc_libs",
    ],
    visibility = ["//visibility:public"],
    deps = [":hdrs"],
)

install(
    name = "install",
    docs = ["LICENSE"],
    visibility = ["//visibility:public"],
    deps = [
        "@drake//tools/workspace/robin_map:install",
    ],
)

exports_files(["drake_repository_metadata.json"])
