function hardware_joint_names = getHardwareJointNames(r)
%NOTEST


hardware_joint_names = {...
      'torsoYaw',...
      'torsoPitch',...
      'torsoRoll',...
      'lowerNeckPitch',...
      'leftHipYaw',...
      'leftHipRoll',...
      'leftHipPitch',...
      'leftKneePitch',...
      'leftAnklePitch',...
      'leftAnkleRoll',...
      'rightHipYaw',...
      'rightHipRoll',...
      'rightHipPitch',...
      'rightKneePitch',...
      'rightAnklePitch',...
      'rightAnkleRoll',...
      'leftShoulderPitch',...
      'leftShoulderRoll',...
      'leftShoulderYaw',...
      'leftElbowPitch',...
      'leftForearm',...
      'leftWristRoll',...
      'leftWristPitch',...
      'rightShoulderPitch',...
      'rightShoulderRoll',...
      'rightShoulderYaw',...
      'rightElbowPitch',...
      'rightForearm',...
      'rightWristRoll',...
      'rightWristPitch'};
