collision_groups_to_keep:
  - heel
  - toe

attachments:
  - frame: r_hand_mount
    urdf: examples/Atlas/urdf/robotiq_tendons.urdf
  - frame: l_hand_mount
    urdf: examples/Atlas/urdf/robotiq_tendons.urdf

