#!/bin/bash

# This program reorganizes Drake's git source tree by moving folders named
# drake-distro/drake/foo to be named drake-distro/foo instead.
#
# TODO(jwnimmer-tri) Remove this script once the #6996 transition is finished.

set -x

# Make sure we're in the right CWD.
test -f WORKSPACE || exit 1
# Make sure we haven't already been run.
test -f drake/.drake-find_resource-sentinel || exit 1

git mv drake/.drake-find_resource-sentinel ./
git mv drake/automotive automotive
git mv drake/bindings bindings
git mv drake/common common
git mv drake/examples examples
git mv drake/geometry geometry
git mv drake/lcm lcm
git mv drake/lcmtypes lcmtypes
git mv drake/manipulation manipulation
git mv drake/math math
git mv drake/multibody multibody
git mv drake/perception perception
git mv drake/solvers solvers
git mv drake/systems systems
git mv drake/util util
git rm drake/BUILD.bazel

perl -pi -e 's/HAS_MOVED_6996 = False/HAS_MOVED_6996 = True/' tools/skylark/6996.bzl
git add tools/skylark/6996.bzl
