FROM ubuntu:16.04
RUN mkdir /drake-distro
COPY . /drake-distro
RUN apt-get update && yes "Y" \
      | /drake-distro/setup/ubuntu/16.04/install_prereqs.sh \
      && rm -rf /var/lib/apt/lists/* \
      && apt-get clean all
RUN cd /drake-distro && bazel build //tools:drake_visualizer && bazel build //examples/acrobot:acrobot_run_passive
ENTRYPOINT ["/drake-distro/setup/docker/entrypoint.sh"]
