# -*- bazel -*-

load("@drake//tools/install:install.bzl", "install")
load("@drake//tools/skylark:cc.bzl", "cc_library")
load("@drake//tools/workspace:vendor_cxx.bzl", "cc_library_vendored")

licenses(["notice"])  # Apache 2.0

package(default_visibility = ["//visibility:public"])

_HDRS = glob(["src/*.h"])

cc_library_vendored(
    name = "uwebsockets",
    hdrs = _HDRS,
    hdrs_vendored = [
        x.replace("src/", "drake_hdr/src/")
        for x in _HDRS
    ],
    includes = ["drake_hdr/src"],
    isystem = True,
    linkopts = ["-pthread"],
    linkstatic = 1,
    deps = [
        "@usockets_internal//:usockets",
        "@zlib",
    ],
)

# Install the license file.
install(
    name = "install",
    docs = ["LICENSE"],
)

exports_files(["drake_repository_metadata.json"])
