# -*- mode: ruby -*-
# vi: set ft=ruby :

tap 'bazelbuild/tap'
tap 'robotlocomotion/director'

brew 'bash-completion'
brew 'bazelbuild/tap/bazel'
brew 'diffstat'
brew 'doxygen'
brew 'freetype'
brew 'graphviz'
brew 'kcov'
brew 'llvm@6'
brew 'patchutils'
brew 'pkg-config'
