# -*- mode: ruby -*-
# vi: set ft=ruby :

tap 'homebrew/cask-fonts' unless File.exist? '/Library/Fonts/DejaVuSans.ttf'
tap 'homebrew/cask-versions' unless system '/usr/libexec/java_home --version 1.8 --failfast &> /dev/null'
tap 'robotlocomotion/director'

cask 'adoptopenjdk8' unless system '/usr/libexec/java_home --version 1.8 --failfast &> /dev/null'
cask 'font-dejavu' unless File.exist? '/Library/Fonts/DejaVuSans.ttf'

brew 'bazel'
brew 'robotlocomotion/director/clang-format@9'
brew 'diffstat'
brew 'doxygen'
brew 'freetype'
brew 'kcov'
brew 'patchutils'
