# -*- python -*-

# This is a list of all *.lcm files in this folder.
# Our BUILD.bazel rules cross-check that it remains up-to-date.
ALL_LCM_SRCS = [
    "experimental_lcmt_deformable_tri.lcm",
    "experimental_lcmt_deformable_tri_mesh_init.lcm",
    "experimental_lcmt_deformable_tri_mesh_update.lcm",
    "experimental_lcmt_deformable_tri_meshes_init.lcm",
    "experimental_lcmt_deformable_tri_meshes_update.lcm",
    "lcmt_acrobot_u.lcm",
    "lcmt_acrobot_x.lcm",
    "lcmt_acrobot_y.lcm",
    "lcmt_allegro_command.lcm",
    "lcmt_allegro_status.lcm",
    "lcmt_call_python.lcm",
    "lcmt_call_python_data.lcm",
    "lcmt_contact_results_for_viz.lcm",
    "lcmt_drake_signal.lcm",
    "lcmt_force_torque.lcm",
    "lcmt_header.lcm",
    "lcmt_hydroelastic_contact_surface_for_viz.lcm",
    "lcmt_hydroelastic_quadrature_per_point_data_for_viz.lcm",
    "lcmt_iiwa_command.lcm",
    "lcmt_iiwa_status.lcm",
    "lcmt_iiwa_status_telemetry.lcm",
    "lcmt_image.lcm",
    "lcmt_image_array.lcm",
    "lcmt_jaco_command.lcm",
    "lcmt_jaco_status.lcm",
    "lcmt_panda_command.lcm",
    "lcmt_panda_status.lcm",
    "lcmt_planar_gripper_command.lcm",
    "lcmt_planar_gripper_finger_command.lcm",
    "lcmt_planar_gripper_finger_face_assignment.lcm",
    "lcmt_planar_gripper_finger_face_assignments.lcm",
    "lcmt_planar_gripper_finger_status.lcm",
    "lcmt_planar_gripper_status.lcm",
    "lcmt_planar_manipuland_status.lcm",
    "lcmt_planar_plant_state.lcm",
    "lcmt_point.lcm",
    "lcmt_point_cloud.lcm",
    "lcmt_point_cloud_field.lcm",
    "lcmt_point_pair_contact_info_for_viz.lcm",
    "lcmt_quaternion.lcm",
    "lcmt_robot_plan.lcm",
    "lcmt_robot_state.lcm",
    "lcmt_schunk_wsg_command.lcm",
    "lcmt_schunk_wsg_status.lcm",
    "lcmt_scope.lcm",
    "lcmt_viewer_command.lcm",
    "lcmt_viewer_draw.lcm",
    "lcmt_viewer_geometry_data.lcm",
    "lcmt_viewer_link_data.lcm",
    "lcmt_viewer_load_robot.lcm",
]
