load("//tools/lint:lint.bzl", "add_lint_tests")
load("//tools/skylark:drake_py.bzl", "drake_py_binary")

drake_py_binary(
    name = "falling_box",
    srcs = ["falling_box.py"],
    deps = ["//bindings/pydrake"],
    add_test_rule = True,
    test_rule_args = [
        "--target_realtime_rate=0",
        "--simulation_time=0.5",
    ],
)

add_lint_tests()
