#!/bin/bash
#
# Drake script to remove the Python venv.

set -eux -o pipefail

# Chdir to the Drake root.
cd "$(dirname $0)/../../.."
readonly venv_root="$(bazel info output_base).venv"

# Remove the venv
rm -r "$venv_root"
