#!/usr/bin/env python3

# This script wraps Drake //tools/wheel:builder; run with --help for more
# details. The main purpose of this script is a) to provide a simpler
# interface, and b) to ensure that the builder knows where the wheel resources
# are located.

import os
import subprocess
import sys


if __name__ == '__main__':
    script_dir = os.path.dirname(os.path.realpath(__file__))

    environment = os.environ.copy()
    environment['DRAKE_WHEEL_RESOURCE_ROOT'] = script_dir

    command = ['bazel', 'run', '//tools/wheel:builder', '--']
    command += sys.argv[1:]

    subprocess.check_call(command, cwd=script_dir, env=environment)
