#!/usr/bin/env python3 -B

# This script builds the PyPI wheels; run with --help for more details. On
# Linux, wheels are build using Docker. On macOS, the host environment is used.

import os
import sys


if __name__ == '__main__':
    script_dir = os.path.dirname(os.path.realpath(__file__))

    sys.path.insert(0, script_dir)
    from drake_wheel_builder.common import entry as main

    if sys.platform == 'darwin':
        import drake_wheel_builder.macos as platform
    else:
        import drake_wheel_builder.linux as platform

    main(args=sys.argv[1:], platform=platform, resource_root=script_dir)
