# A source archive embeds "<version> <sha>" here. An explicit override still
# wins over it, so a stray copy can't mask CI intent.
set(PACKAGE_VERSION_FILE "${CMAKE_CURRENT_LIST_DIR}/PACKAGE_VERSION.TXT")
if(EXISTS "${PACKAGE_VERSION_FILE}")
  file(READ "${PACKAGE_VERSION_FILE}" PACKAGE_VERSION_CONTENT)
  string(STRIP "${PACKAGE_VERSION_CONTENT}" PACKAGE_VERSION_CONTENT)
  string(REPLACE " " ";" PACKAGE_VERSION_PARTS "${PACKAGE_VERSION_CONTENT}")
  list(GET PACKAGE_VERSION_PARTS 0 PACKAGE_DRAKE_VERSION)
  list(GET PACKAGE_VERSION_PARTS 1 PACKAGE_GIT_REVISION)
endif()

set(GIT_REVISION HEAD)
set(BUILD_IDENTIFIER unknown)

if(DEFINED DRAKE_GIT_SHA_OVERRIDE)
  set(GIT_REVISION "${DRAKE_GIT_SHA_OVERRIDE}")
elseif(DEFINED PACKAGE_GIT_REVISION)
  set(GIT_REVISION "${PACKAGE_GIT_REVISION}")
else()
  if(GIT_EXECUTABLE AND EXISTS "${GIT_DIR}")
    execute_process(COMMAND
      "${GIT_EXECUTABLE}" "--git-dir=${GIT_DIR}" rev-parse HEAD
      RESULT_VARIABLE GIT_REV_PARSE_RESULT_VARIABLE
      OUTPUT_VARIABLE GIT_REV_PARSE_OUTPUT_VARIABLE
      OUTPUT_STRIP_TRAILING_WHITESPACE
    )

    if(GIT_REV_PARSE_RESULT_VARIABLE EQUAL 0)
      set(GIT_REVISION "${GIT_REV_PARSE_OUTPUT_VARIABLE}")
      string(SUBSTRING ${GIT_REVISION} 0 8 GIT_REVISION_SHORT)
      set(BUILD_IDENTIFIER git${GIT_REVISION_SHORT})
    endif()
  endif()
endif()

if(DEFINED DRAKE_VERSION_OVERRIDE)
  set(DRAKE_VERSION "${DRAKE_VERSION_OVERRIDE}")
elseif(DEFINED PACKAGE_DRAKE_VERSION)
  set(DRAKE_VERSION "${PACKAGE_DRAKE_VERSION}")
else()
  string(TIMESTAMP BUILD_TIMESTAMP "%Y%m%d.%H%M%S")
  string(REGEX REPLACE "[.]0+([0-9])" ".\\1"
    DRAKE_VERSION "0.0.${BUILD_TIMESTAMP}+${BUILD_IDENTIFIER}")
endif()

configure_file(${INPUT_FILE} ${OUTPUT_FILE} @ONLY)
