#pragma once

#include <limits>
#include <vector>

#include "drake/common/drake_copyable.h"
#include "drake/common/eigen_types.h"
#include "drake/examples/mass_spring_cloth/gen/cloth_spring_model_params.h"
#include "drake/systems/framework/leaf_system.h"

namespace drake {
namespace examples {
namespace mass_spring_cloth {
/** A system that models a rectangular piece of cloth using as a model a
 structured grid of springs and dampers. The system consists of nx-by-ny mass
 points with neighboring points separated by a distance of h meters. The
 rectangular grid initially lies in the z=0 plane and is fixed at two corners at
 (0,0,0) and (0, (ny-1)*h, 0). Shearing springs are added to penalize shearing
 modes. The model is described in detail in [Provot 1995] Provot, Xavier.
 "Deformation constraints in a mass-spring model to describe rigid cloth
 behaviour." Graphics interface. Canadian Information Processing Society, 1995.

 The system has three physical parameters:
 k: elastic stiffness of the springs in the unit of N/m, measures the elastic
 force generated by the spring per unit displacement from the rest length.

 d: damping coefficient of the springs in the unit of Ns/m, measures the damping
 force generated by the spring per unit relative velocity of the two points
 connected by the spring.

 gravity: the gravitational constant, a (usually negative) scalar. The gravity
 experienced by the mass points is (0,0,gravity) along the z-axis.

 The dynamics of the system is described by:
 ẋ = v,
 Mv̇ = f(x,v).

 When the system is integrated discretely, the elastic force and gravity is
 integrate explicitly while the damping force is integrate implicitly to obrain
 a linear system as described in
 [Bridson, 2005] Bridson, Robert, Sebastian
 Marino, and Ronald Fedkiw. "Simulation of clothing with folds and wrinkles."
 ACM SIGGRAPH 2005 Courses. 2005.
 One should be careful not to take too large a timestep when the system is
 integrated discretely to prevent inverting the springs.

 @system
 name: ClothSpringModel
 output_ports:
 - states
 @endsystem
*/
template <typename T>
class ClothSpringModel final : public systems::LeafSystem<T> {
 public:
  DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(ClothSpringModel)

  /** Creates a rectangular cloth with a grid of nx by ny points and initialize
   their velocity to 0.

   @param[in] nx number of points in the x-direction.
   @param[in] ny number of points in the y-direction.
   @param[in] h in m units is the spacing between neighboring points.
   @param[in] dt in s unit is the time step of the discrete solver. If dt < 0,
   the continuous solver will be used.
   */
  ClothSpringModel(int nx, int ny, T h, double dt);

  void InitializePositionAndVelocity(systems::Context<T>* context);

  int get_num_points() const { return num_points_; }

 private:
  struct Spring {
    int node0, node1;  // Indices of the two nodes.
    T rest_length;
  };

  int nx_{};            // Number of points in the x direction.
  int ny_{};            // Number of points in the y direction.
  int num_points_{};    // Total number of mass points.
  T h_{};              // The distance between neighboring mass points.
  T dt_{};              // The time period between discrete updates.
  int left_corner_{};   // Index of the fixed top-left corner of the grid.
  int right_corner_{};  // Index of the fixed top-right corner of the grid.
  int param_offset_{};  // The starting index of the parameters of this system.
  mutable Eigen::SparseMatrix<T>
      H_;  // Pre-allocated H matrix to prevent reallocations.
  std::vector<Spring> springs_;  // A list of springs in the system. Indexing
  // does not matter here.
  mutable Eigen::ConjugateGradient<Eigen::SparseMatrix<double>,
                                   Eigen::Lower | Eigen::Upper>
      cg_;  // We use a CG solver for the symmetric positive definite matrix in
  // the linear solve. We use the Lower|Upper flag for better
  // performance per Eigen Doc:
  // https://eigen.tuxfamily.org/dox/classEigen_1_1ConjugateGradient.html

  template <class VectorType>
  void InitializePositionAndVelocity(int nx, int ny, T h, VectorType* x,
                                     VectorType* v) const {
    DRAKE_DEMAND(x->size() == 3 * nx * ny && v->size() == 3 * nx * ny);
    for (int i = 0; i < nx; ++i) {
      for (int j = 0; j < ny; ++j) {
        int node_index = i * ny + j;
        (*x)[3 * node_index] = i * h;
        (*x)[3 * node_index + 1] = j * h;
        (*x)[3 * node_index + 2] = 0.0;
        (*v)[3 * node_index] = 0.0;
        (*v)[3 * node_index + 1] = 0.0;
        (*v)[3 * node_index + 2] = 0.0;
      }
    }
  }

  // TODO(xuchenhan-tri) Expose this in follow-up PR.
  // Generates the connectivity of the mesh of springs.
  void BuildRectanglePatch(bool use_shearing_springs);

  void CopyContinuousStateOut(const systems::Context<T>& context,
                              systems::BasicVector<T>* output) const;

  void CopyDiscreteStateOut(const systems::Context<T>& context,
                            systems::BasicVector<T>* output) const;

  void DoCalcTimeDerivatives(
      const systems::Context<T>& context,
      systems::ContinuousState<T>* derivatives) const override;

  void UpdateDiscretePositionAndVelocity(
      const systems::Context<T>& context,
      systems::DiscreteValues<T>* next_states) const;

  // Calculates the spring (elastic and damping combined) forces given the
  // context.
  void CalcSpringForce(const systems::Context<T>& context,
                       systems::VectorBase<T>* forces) const;

  const ClothSpringModelParams<T>& get_parameters(
      const systems::Context<T>& context) const {
    return this->template GetNumericParameter<ClothSpringModelParams>(
        context, param_offset_);
  }

  // Calculates the elastic force from springs given the positions of the nodes
  // and add to the output elastic_force. The values contained in elastic_force
  // should be set to zero outside this function if fresh values are required.
  //
  // ``PositionVectorType``, ``VelocityVectorType`` and ``ForceVectorType`` are
  // placeholders for systems::VectorBase<T> and Eigen::VectorBlock<VectorX<T>>
  // to accomodate different data types from discrete and continuous solvers.
  template <class PositionVectorType, class ForceVectorType>
  void AccumulateElasticForce(const ClothSpringModelParams<T>& param,
                              const PositionVectorType& x,
                              ForceVectorType* elastic_force) const {
    for (const Spring& s : springs_) {
      // Get the positions of the two mass points connected by the spring.
      const int n0 = s.node0;
      const int n1 = s.node1;
      const Vector3<T> p_Wx0 =
          Vector3<T>(x[3 * n0], x[3 * n0 + 1], x[3 * n0 + 2]);
      const Vector3<T> p_Wx1 =
          Vector3<T>(x[3 * n1], x[3 * n1 + 1], x[3 * n1 + 2]);
      const Vector3<T> p_x0x1_W = p_Wx1 - p_Wx0;
      const T p_x0x1_W_norm = p_x0x1_W.norm();
      constexpr double kRelativeTolerance =
          10 * std::numeric_limits<double>::epsilon();
      DRAKE_THROW_UNLESS(p_x0x1_W_norm > kRelativeTolerance * s.rest_length);
      const Vector3<T> n = p_x0x1_W / p_x0x1_W_norm;
      // If the n is the unit vector point from x0 to x1,
      // the spring elastic force = k * (current_length - rest_length) * n
      const Vector3<T> f = param.k() * (p_x0x1_W_norm - s.rest_length) * n;
      for (int j = 0; j < 3; ++j) {
        (*elastic_force)[3 * n0 + j] += f[j];
        (*elastic_force)[3 * n1 + j] -= f[j];
      }
    }
  }

  // Calculates the damping force from springs given the positions and
  // velocities of the nodes and add to the output damping_force. The values
  // contained in damping_force should be set to zero outside this function if
  // fresh values are required.
  template <class PositionVectorType, class VelocityVectorType,
            class ForceVectorType>
  void CalcDampingForce(const ClothSpringModelParams<T>& param,
                        const PositionVectorType& x,
                        const VelocityVectorType& v,
                        ForceVectorType* damping_force) const {
    for (const Spring& s : springs_) {
      // Get the positions and velocities of the two mass points connected by
      // the spring.
      const int n0 = s.node0;
      const int n1 = s.node1;
      const Vector3<T> p_Wx0 =
          Vector3<T>(x[3 * n0], x[3 * n0 + 1], x[3 * n0 + 2]);
      const Vector3<T> p_Wx1 =
          Vector3<T>(x[3 * n1], x[3 * n1 + 1], x[3 * n1 + 2]);
      const Vector3<T> p_Wv0 =
          Vector3<T>(v[3 * n0], v[3 * n0 + 1], v[3 * n0 + 2]);
      const Vector3<T> p_Wv1 =
          Vector3<T>(v[3 * n1], v[3 * n1 + 1], v[3 * n1 + 2]);
      const Vector3<T> p_x0x1_W = p_Wx1 - p_Wx0;
      const T p_x0x1_W_norm = p_x0x1_W.norm();
      constexpr double kRelativeTolerance =
          10 * std::numeric_limits<double>::epsilon();
      DRAKE_THROW_UNLESS(p_x0x1_W_norm > kRelativeTolerance * s.rest_length);
      const Vector3<T> n = p_x0x1_W / p_x0x1_W_norm;
      // If the n is the unit vector point from x0 to x1,
      // the damping force = (damping coefficient * velocity difference)
      // projected in the direction of n.
      const Vector3<T> f = param.d() * (p_Wv1 - p_Wv0).dot(n) * n;
      for (int j = 0; j < 3; ++j) {
        (*damping_force)[3 * n0 + j] += f[j];
        (*damping_force)[3 * n1 + j] -= f[j];
      }
    }
  }

  // Calculates the change in velocity, dv = vⁿ⁺¹ - v̂, induced by the implicit
  // damping force, where v̂ is the velocity after the contribution of elastic
  // and gravity forces are added. The momentum equation M * dv = f(vⁿ⁺¹) * dt,
  // where f is the damping force, is equivalent to
  // M * dv = (f(v̂) + ∂f/∂v(v̂) * dv) * dt, because damping force is linear in
  // v. Moving terms, we end up with
  // (M - ∂f/∂v(v̂)) * dv = f(v̂) * dt which we abbreviate as
  // H * dv = f * dt.
  template <class PositionVectorType, class VelocityVectorType,
            class ForceVectorType>
  void CalcDv(const ClothSpringModelParams<T>& param,
              const PositionVectorType& x, const ForceVectorType& f,
              VelocityVectorType* dv) const {
    const T mass_per_point = param.mass() / static_cast<T>(num_points_);
    // Initialize the diagonal of the matrix to be mass_per_point.
    for (int i = 0; i < num_points_; ++i) {
      for (int j = 0; j < 3; ++j) {
        for (int k = 0; k < 3; ++k) {
          H_.coeffRef(3 * i + j, 3 * i + k) =
              (j == k) ? mass_per_point : static_cast<T>(0.0);
        }
      }
    }
    // Add in the contribution from damping force differential.
    for (const Spring& s : springs_) {
      // Get the positions of the two mass points connected by the spring.
      const int n0 = s.node0;
      const int n1 = s.node1;
      const Vector3<T> p_Wx0 =
          Vector3<T>(x[3 * n0], x[3 * n0 + 1], x[3 * n0 + 2]);
      const Vector3<T> p_Wx1 =
          Vector3<T>(x[3 * n1], x[3 * n1 + 1], x[3 * n1 + 2]);
      const Vector3<T> p_x0x1_W = p_Wx1 - p_Wx0;
      const T p_x0x1_W_norm = p_x0x1_W.norm();
      const Vector3<T> n = p_x0x1_W / p_x0x1_W_norm;
      // If the n is the unit vector point from x0 to x1,
      // the spring elastic force = elastic stiffness * (length - restlength) *
      // n, and damping force = (damping coefficient * velocity difference)
      // projected in the direction of n.
      const Matrix3<T> damping_force_derivative =
          param.d() * dt_ * n * n.transpose();

      // Equivalent to the unsupported operation:
      // H_.block<3,3>(3*n0, 3*n0) += damping_force_derivative;
      // H_.block<3,3>(3*n1, 3*n1) += damping_force_derivative;
      // H_.block<3,3>(3*n0, 3*n1) = -damping_force_derivative;
      // H_.block<3,3>(3*n1, 3*n0) = -damping_force_derivative;
      for (int j = 0; j < 3; ++j) {
        for (int k = 0; k < 3; ++k) {
          // The diagonal blocks get contribution from multiple springs. We can
          // safely add to the diagonal blocks because they were reset earlier.
          H_.coeffRef(3 * n0 + j, 3 * n0 + k) += damping_force_derivative(j, k);
          H_.coeffRef(3 * n1 + j, 3 * n1 + k) += damping_force_derivative(j, k);
          // Do not add in the off-diagonal terms involving fixed nodes.
          if (n0 != left_corner_ && n0 != right_corner_ && n1 != left_corner_ &&
              n1 != right_corner_) {
            // Each off-diagonal block only gets contribution from a single
            // spring. It's important to overwrite the value from previous
            // time-step.
            H_.coeffRef(3 * n1 + j, 3 * n0 + k) =
                -damping_force_derivative(j, k);
            H_.coeffRef(3 * n0 + j, 3 * n1 + k) =
                -damping_force_derivative(j, k);
          }
        }
      }
    }
    cg_.compute(H_);
    // Solve H * dv = f * dt.
    (*dv) = cg_.solve(f * dt_);
  }

  /// Apply Dirichlet boundary conditions to the two corners of the rectangular
  /// grid.
  template <class VectorType>
  void ApplyDirichletBoundary(VectorType* state) const {
    for (int d = 0; d < 3; ++d) {
      (*state)[3 * left_corner_ + d] = T(0);
      (*state)[3 * right_corner_ + d] = T(0);
    }
  }
};
}  // namespace mass_spring_cloth
}  // namespace examples
}  // namespace drake
