#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import os
import sys


def main():
    prefix = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    sys.path.insert(0, os.path.join(
        prefix, 'lib',
        'python{}.{}'.format(sys.version_info.major, sys.version_info.minor),
        'site-packages'))

    import meshcat.servers.zmqserver

    meshcat.servers.zmqserver.main()


if __name__ == '__main__':
    main()
