#!/bin/bash
#
# Install Drake prerequisites.

set -euo pipefail

# This script should be run as the normal user (i.e., `setup/install_prereqs`),
# not under sudo (i.e., not `sudo setup/install_prereqs`). On the other hand, if
# the normal user *is* the root user (e.g., inside Docker) then we allow it, or
# if sudo is being used to switch users (i.e., `sudo -u otheruser ...`) then we
# allow it. The only mistake we're trying to catch here is accidentally using
# `sudo` out of habit (since that's what Drake previously required).
if [[ "${EUID}" -eq 0 && -n "${SUDO_USER:+D}" ]]; then
  echo 'This script must NOT be run through sudo' >&2
  exit 1
fi

# While we're halfway through rewriting our setup scripts to Python, the command
# line arguments need to go to specific helper scripts.
mac_sh_args=()
py_args=()
with_update=1
maybe_yes=""
user_environment_only=0
while [ "${1:-}" != "" ]; do
  case "$1" in
    --user-environment-only)
      user_environment_only=1
      py_args+=("$1")
      ;;
    --verbose)
      py_args+=("$1")
      ;;
    --without-update)
      with_update=0
      mac_sh_args+=("$1")
      py_args+=("$1")
      ;;
    -y)
      maybe_yes="-y"
      py_args+=("$1")
      ;;
    *)
      mac_sh_args+=("$1")
      py_args+=("$1")
      ;;
  esac
  shift
done

# Call the helper script(s). The first step bootstraps Python if necessary; the
# second step uses the Python installed by the first one.
if [[ "$(uname)" == "Darwin" ]]; then
  # N.B. We need `${var:0}` throughout this section because macOS's older
  # version of bash does not seem to be able to cope with an empty array.
  if [[ "${user_environment_only}" -eq 0 ]]; then
    /bin/bash "${BASH_SOURCE%/*}/mac/install_prereqs.sh" "${mac_sh_args[@]:0}"
  fi
  exec $(brew --prefix)/bin/python3.14 -B "${BASH_SOURCE%/*}/install_prereqs.py" "${py_args[@]:0}"
else
  if [[ "${user_environment_only}" -eq 0 ]]; then
    if ! command -v python3 > /dev/null; then
      echo "Installing python3 ..." >&2
      maybe_sudo=
      if [[ "${EUID}" -ne 0 ]]; then
        maybe_sudo=sudo
      fi
      if ! ${maybe_sudo} apt-get install ${maybe_yes} --no-install-recommends python3; then
        if [[ "${with_update}" -eq 1 ]]; then
          ${maybe_sudo} apt-get update || (sleep 30; ${maybe_sudo} apt-get update) || (cat <<EOF && false)
****************************************************************************
Drake is unable to run 'sudo apt-get update', probably because this computer
contains incorrect entries in its sources.list files, or possibly because an
internet service is down.

Run 'sudo apt-get update' and try to resolve whatever problems it reports.
Do not try to set up Drake until that command succeeds.

This is not a bug in Drake. Do not contact the Drake team for help.
****************************************************************************
EOF
        fi
        ${maybe_sudo} apt-get install ${maybe_yes} --no-install-recommends python3
      fi
    fi
  fi
  exec python3 -B "${BASH_SOURCE%/*}/install_prereqs.py" "${py_args[@]}"
fi
