#!/bin/bash
#
# Install Drake prerequisites. This script is a small bash trampoline which
# first installs Python (if missing) and then uses Python for the remainder of
# the installation.
#
# TODO(jwnimmer-tri) The "small bash trampoline" is currently only true on
# Linux. For macOS, we still defer to the lecacy script, instead.

set -euo pipefail

# This script should be run as the normal user (i.e., `setup/install_prereqs`),
# not under sudo (i.e., not `sudo setup/install_prereqs`). On the other hand, if
# the normal user *is* the root user (e.g., inside Docker) then we allow it, or
# if sudo is being used to switch users (i.e., `sudo -u otheruser ...`) then we
# allow it. The only mistake we're trying to catch here is accidentally using
# `sudo` out of habit (since that's what Drake previously required).
if [[ "${EUID}" -eq 0 && -n "${SUDO_USER:+D}" ]]; then
  echo 'This script must NOT be run through sudo' >&2
  exit 1
fi

# TODO(jwnimmer-tri) We should port the macOS code to Python, too.
if [[ "$(uname)" == "Darwin" ]]; then
  exec "${BASH_SOURCE%/*}/mac/install_prereqs.sh" "$@"
fi

# We need a Python interpreter.
if ! command -v python3 > /dev/null; then
  echo "Installing python3 ..." >&2
  maybe_sudo=
  if [[ "${EUID}" -ne 0 ]]; then
    maybe_sudo=sudo
  fi
  if ! ${maybe_sudo} apt-get -y install python3; then
    ${maybe_sudo} apt-get update || (sleep 30; apt-get update)
    ${maybe_sudo} apt-get -y install python3
  fi
fi

# Switch over to the Python script now, passing along all arguments.
exec python3 -B "${BASH_SOURCE%/*}/install_prereqs.py" "$@"
