# -*- python -*-

# N.B. This has the "wrong" name `BUILD`, because it is a temporary artifact;
# soon, it will be replaced with a `BUILD.bazel` moved from elsewhere.
#
# TODO(jwnimmer-tri) Move drake/tools/BUILD.bazel to replace this.

package(default_visibility = ["//visibility:public"])

load("//tools/lint:lint.bzl", "add_lint_tests")

add_lint_tests()
