load("@drake//tools/skylark:cc_hidden.bzl", "cc_static_hidden_library")
load("//tools/install:install.bzl", "install", "install_files")
load("//tools/lint:lint.bzl", "add_lint_tests")

package(default_visibility = ["//visibility:private"])

install_files(
    name = "install_license",
    dest = "share/doc/suitesparse",
    files = ["@module_suitesparse//:AMD/Doc/License.txt"],
    allowed_externals = ["@module_suitesparse//:AMD/Doc/License.txt"],
)

install(
    name = "install",
    visibility = ["//tools/workspace:__pkg__"],
    deps = [":install_license"],
)

add_lint_tests()
