#pragma once

#include <string>
#include <utility>
#include <vector>

#include "ignition/math/Vector3.hh"
#include "ignition/rndf/UniqueId.hh"

#include "drake/common/drake_copyable.h"
#include "drake/common/drake_throw.h"

namespace drake {
namespace maliput {
namespace rndf {

/// A container that holds the information needed by a Builder to construct a
/// Lane from a sequence of ignition::rndf::Waypoint objects.
class DirectedWaypoint {
 public:
  DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(DirectedWaypoint)

  DirectedWaypoint() = default;

  /// Constructor.
  /// @param id RNDF waypoint's ID. It may be generated by the Builder or a copy
  /// of what has been parsed by ignition::rndf::RNDF.
  /// @param position The 3D coordinates of the knot in the api::GeoPosition
  /// frame.
  /// @param tangent The tangent vector at @p position in the api::GeoPosition
  /// frame.
  /// @param is_entry True if the original RNDF waypoint acts as the entry for
  /// the RNDF lane.
  /// @param is_exit True if the original RNDF waypoint acts as the exit for the
  /// RNDF lane.
  DirectedWaypoint(const ignition::rndf::UniqueId& id,
                   const ignition::math::Vector3d& position,
                   const ignition::math::Vector3d& tangent, bool is_entry,
                   bool is_exit)
      : id_(id),
        position_(position),
        tangent_(tangent),
        is_entry_(is_entry),
        is_exit_(is_exit) {}

  const ignition::rndf::UniqueId& id() const { return id_; }

  void set_id(const ignition::rndf::UniqueId& id) { id_ = id; }

  const ignition::math::Vector3d& position() const { return position_; }

  void set_position(const ignition::math::Vector3d& position) {
    position_ = position;
  }

  const ignition::math::Vector3d& tangent() const { return tangent_; }

  void set_tangent(const ignition::math::Vector3d& tangent) {
    tangent_ = tangent;
  }

  bool is_entry() const { return is_entry_; }

  void set_is_entry(bool is_entry) { is_entry_ = is_entry; }

  bool is_exit() const { return is_exit_; }

  void set_is_exit(bool is_exit) { is_exit_ = is_exit; }

  /// Gets the bounding box of a vector of @p directed_waypoints. It
  /// gets the minimum and maximum x and y coordinates from all the items.
  /// z coordinate will always be zero as RNDF is a flat map.
  /// @param directed_waypoints A vector of DirectedWaypoints whose positions
  /// are evaluated to define the corners of a bounding box that holds them.
  /// @return A std::pair that holds two diagonal corners of the bounding box
  /// that encloses @p directed_waypoints. The pair's first value is the
  /// minimum x and y coordinate and the second value is the maximum x and y
  /// coordinate. When @p directed_waypoints is an empty vector, the pair
  /// values are both zero vectors.
  static std::pair<ignition::math::Vector3d, ignition::math::Vector3d>
  CalculateBoundingBox(const std::vector<DirectedWaypoint>& directed_waypoints);

 private:
  // The ID.
  ignition::rndf::UniqueId id_;
  // A 3D vector which is the coordinate of the waypoint in the api::GeoPosition
  // frame.
  ignition::math::Vector3d position_;
  // A 3D vector which is the tangent of the waypoint at position_.
  ignition::math::Vector3d tangent_;
  // Tells whether or not the original RNDF waypoint acts as an entry for the
  // RNDF lane.
  bool is_entry_{false};
  // Tells whether or not the original RNDF waypoint acts as an exit for the
  // RNDF lane.
  bool is_exit_{false};
};

/// A container that holds the information needed by a Builder to construct a
/// Lane. This class will be created from DirectedWaypoints (based on RNDF
/// waypoints that belong to the same RNDF lane).
/// A Connection object may derive in one or multiple Lanes. Consequently the
/// list of waypoints require to have at least two valid (related to the
/// DirectedWaypoint's ignition::rndf::UniqueId) waypoints to derive a
/// interpolated geometry from them. The order the waypoints are set, is the
/// way they will be used so create an interpolated curve (base line of the
/// Lane). Lane's width is fixed along the complete path length.
/// Builder class will receive a group of Connections that belong to the same
/// RNDF segment. Note that RNDF has no constraint on lanes direction inside a
/// segment, so Connections should be marked to group them by sense of
/// flow.
class Connection {
 public:
  DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(Connection)
  /// Constructs a Connection.
  /// @param id Connection's ID.
  /// @param waypoints A DirectedWaypoints vector that determines the lane path.
  /// @param width The Lane's width.
  /// @param inverse_direction False if this Connection belongs to a group of
  /// Connections and the sense of direction of this Connection is the same as
  /// the first Connection in the group. The first Connection will be set False
  /// as default.
  /// @throws std::runtime_error When the number of @p waypoints items, whose
  /// ignition::rndf::UniqueId is valid, is less than 2.
  /// @throws std::runtime_error When the @p width is less or equal to 0.0.
  Connection(const std::string& id,
             const std::vector<DirectedWaypoint>& waypoints,
             double width, bool inverse_direction)
      : id_(id),
        waypoints_(waypoints),
        width_(width),
        inverse_direction_(inverse_direction) {
    ThrowIfInvalidWaypoints(waypoints);
    DRAKE_THROW_UNLESS(width > 0.0);
  }

  /// Getter of the ID.
  /// @return The ID.
  const std::string& id() const { return id_; }

  /// Getter of the first item in DirectedWaypoint vector.
  /// @return A constant reference to the first item in DirectedWaypoint vector.
  const DirectedWaypoint& start() const { return waypoints_.front(); }

  /// Getter of the last item in DirectedWaypoint vector.
  /// @return A constant reference to the last item in DirectedWaypoint vector.
  const DirectedWaypoint& end() const { return waypoints_.back(); }

  /// Getter of the DirectedWaypoint vector.
  /// @return The DirectedWaypoint vector.
  const std::vector<DirectedWaypoint>& waypoints() const { return waypoints_; }

  /// Setter of the DirectedWaypoint vector.
  /// @param waypoints A vector of DirectedWaypoints.
  /// @throws std::runtime_error When @p waypoints holds less than two valid
  /// DirectedWaypoints.
  void set_waypoints(const std::vector<DirectedWaypoint>& waypoints) {
    ThrowIfInvalidWaypoints(waypoints);
    waypoints_ = waypoints;
  }

  /// Adds a waypoint to the DirectedWaypoint vector at @p position index.
  /// @param waypoint A DirectedWaypoint to add.
  /// @param position The index in the DirectedWaypoint vector at which
  /// @p waypoint should be added.
  /// @throws std::runtime_error When position is less than 0.
  /// @throws std::runtime_error When position is greater than the size of the
  /// DirectedWaypoint vector.
  void AddWaypoint(const DirectedWaypoint& waypoint, int position);

  /// Getter for the width.
  /// @return The width.
  double width() const { return width_; }

  /// Setter for the width.
  /// @param width The absolute span from one lateral extent to the other of the
  /// api::Lane that the Builder will make from this Connection.
  /// @throws std::runtime_error When @p width is less or equal to zero.
  void set_width(double width) {
    DRAKE_THROW_UNLESS(width > 0.0);
    width_ = width;
  }

  /// Getter of inverse_direction.
  /// @return true when this Connection has inverse direction relative to the
  /// base Lane in the RNDF segment to which this Connection belongs, and false
  /// otherwise.
  bool inverse_direction() const { return inverse_direction_; }

  /// Setter of inverse_direction.
  /// @brief inverse_direction The relative direction regarding another
  /// Connection which will be considered as the reference direction for the
  /// RNDF segment.
  void set_inverse_direction(bool inverse_direction) {
    inverse_direction_ = inverse_direction;
  }

 private:
  // Throws an exception if @waypoints doesn't hold at least two valid
  // waypoints.
  // @param waypoints A vector of DirectedWaypoints to check.
  // @throws std::runtime_error When @p waypoints holds less than two valid
  // DirectedWaypoints.
  void ThrowIfInvalidWaypoints(
      const std::vector<DirectedWaypoint>& waypoints) const {
    int num_valid = 0;
    for (const DirectedWaypoint& wp : waypoints) {
      if (wp.id().Valid()) {
        num_valid++;
        if (num_valid == 2) {
          return;
        }
      }
    }
    DRAKE_THROW_UNLESS(num_valid > 1);
  }

  // The ID.
  std::string id_;
  // A vector that holds the sequence of the DirectedWaypoints.
  std::vector<DirectedWaypoint> waypoints_;
  // The width of the connection.
  double width_{};
  // A boolean that tells if this connection has an inverse direction relative
  // to another connection which is inside the same RNDF segment and that
  // represents the first lane in the segment.
  bool inverse_direction_{false};
};

}  // namespace rndf
}  // namespace maliput
}  // namespace drake
