#pragma once

#include <string>
#include <tuple>
#include <vector>

#include "ignition/math/Vector3.hh"
#include "ignition/rndf/UniqueId.hh"

#include "drake/common/drake_copyable.h"
#include "drake/common/drake_throw.h"

namespace drake {
namespace maliput {
namespace rndf {

/// A container that holds the information needed by a Builder to construct a
/// Lane from a sequence of ignition::rndf::Waypoint objects.
class DirectedWaypoint {
 public:
  DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(DirectedWaypoint)
  /// Default constructor.
  DirectedWaypoint() = default;

  /// Constructor.
  ///
  /// @param id RNDF waypoint's ID. It may be generated by the Builder or a copy
  /// of what has been parsed by ignition::rndf::RNDF.
  /// @param position The 3D coordinates of the knot in the api::GeoPosition
  /// frame.
  /// @param tangent The tangent vector at @p position.
  /// @param is_entry Whether or not the original RNDF waypoint acts as the
  /// entry for the RNDF lane.
  /// @param is_exit Whether or not the original RNDF waypoint acts as the exit
  /// for the RNDF lane.
  DirectedWaypoint(const ignition::rndf::UniqueId& id,
                   const ignition::math::Vector3d& position,
                   const ignition::math::Vector3d& tangent, bool is_entry,
                   bool is_exit)
      : id_(id),
        position_(position),
        tangent_(tangent),
        is_entry_(is_entry),
        is_exit_(is_exit) {}

  /// Getter of the ID.
  /// @return An const reference to the ID.
  const ignition::rndf::UniqueId& id() const { return id_; }

  /// Setter of the ID.
  /// @param id The ID.
  void set_id(const ignition::rndf::UniqueId& id) { id_ = id; }

  /// Getter of the position.
  /// @return The position.
  const ignition::math::Vector3d& position() const { return position_; }

  /// Setter of the position.
  /// @param position The 3D coordinates of the knot in the api::GeoPosition
  /// frame.
  void set_position(const ignition::math::Vector3d& position) {
    position_ = position;
  }

  /// Getter of the tangent.
  /// @return The tangent vector.
  const ignition::math::Vector3d& tangent() const { return tangent_; }

  /// Setter of the tangent.
  /// @param tangent The tangent vector.
  void set_tangent(const ignition::math::Vector3d& tangent) {
    tangent_ = tangent;
  }

  /// Getter of is_entry.
  /// @return true if this waypoint is an entry and false otherwise.
  bool is_entry() const { return is_entry_; }

  /// Setter of is_entry.
  /// @param is_entry Whether or not the original RNDF waypoint acts as the
  /// entry for the RNDF lane.
  void set_is_entry(bool is_entry) { is_entry_ = is_entry; }

  /// Getter of is_exit.
  /// @return true if this waypoint is an exit and false otherwise.
  bool is_exit() const { return is_exit_; }

  /// Setter of is_exit.
  /// @param is_entry Whether or not the original RNDF waypoint acts as the
  /// exit for the RNDF lane.
  void set_is_exit(bool is_exit) { is_exit_ = is_exit; }

  /// Gets the bounding box of a vector of @p directed_waypoints. It
  /// gets the minimum and maximum x and y coordinates from all the items.
  /// z coordinate will always be zero as RNDF is a flat map.
  /// @param directed_waypoints A vector of DirectedWaypoints whose positions
  /// are evaluated to define the corners of a bounding box that holds them.
  /// @return A std::tuple that holds two diagonal corners of the bounding box
  /// that encloses @p directed_waypoints. The tuple's first value is the
  /// minimum x and y coordinate and the second value is the maximum x and y
  /// coordinate. Coordinates are separately evaluated. When
  /// @p directed_waypoints is an empty vector, the tuple values are both vector
  /// of zeros.
  static std::tuple<ignition::math::Vector3d, ignition::math::Vector3d>
  CalculateBoundingBox(const std::vector<DirectedWaypoint>& directed_waypoints);

 private:
  // The ID.
  ignition::rndf::UniqueId id_;
  // A 3D vector which is the coordinate of the waypoint in the api::GeoPosition
  // frame.
  ignition::math::Vector3d position_;
  // A 3D vector which is the tangent of the waypoint at position_.
  ignition::math::Vector3d tangent_;
  // Tells whether or not the original RNDF waypoint acts as an entry for the
  // RNDF lane.
  bool is_entry_{false};
  // Tells whether or not the original RNDF waypoint acts as an exit for the
  // RNDF lane.
  bool is_exit_{false};
};

/// A container that holds the information needed by a Builder to construct a
/// Lane.
class Connection {
 public:
  DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(Connection)
  /// Constructs a Connection.
  ///
  /// @param id Connection's ID.
  /// @param waypoints A DirectedWaypoints vector that determines the lane path.
  /// @param width The Lane's width.
  /// @param inverse_direction Keeps track of the relative sense of direction
  /// (given by how @p waypoints are set) with respect to other Connection. RNDF
  /// has a similar abstraction for Segments and Lanes but it allows Lanes
  /// flowing in different directions inside the same Segment. Consequently,
  /// Builder must group Connections that flow in the same direction.
  /// @throws std::runtime_error When the number of @p waypoints items, whose
  /// ignition::rndf::UniqueId is valid, is less than 2.
  /// @throws std::runtime_error When the @p width is less or equal to 0.0.
  explicit Connection(const std::string& id,
                      const std::vector<DirectedWaypoint>& waypoints,
                      double width, bool inverse_direction)
      : id_(id),
        waypoints_(waypoints),
        width_(width),
        inverse_direction_(inverse_direction) {
    CheckWaypoints(waypoints);
    DRAKE_THROW_UNLESS(width > 0.0);
  }

  /// Getter of the ID.
  /// @return The ID.
  const std::string& id() const { return id_; }

  /// Getter of the first item in DirectedWaypoint vector.
  /// @return A constant reference to the first item in DirectedWaypoint vector.
  const DirectedWaypoint& start() const { return waypoints_.front(); }

  /// Getter of the last item in DirectedWaypoint vector.
  /// @return A constant reference to the last item in DirectedWaypoint vector.
  const DirectedWaypoint& end() const { return waypoints_.back(); }

  /// Getter of the DirectedWaypoint vector.
  /// @return The DirectedWaypoint vector.
  const std::vector<DirectedWaypoint>& waypoints() const { return waypoints_; }

  /// Setter of the DirectedWaypoint vector.
  /// @param waypoints A vector of DirectedWaypoints.
  /// @throws std::runtime_error When @p waypoints holds less than two valid
  /// DirectedWaypoints.
  void set_waypoints(const std::vector<DirectedWaypoint>& waypoints) {
    CheckWaypoints(waypoints);
    waypoints_ = waypoints;
  }

  /// Adds a waypoint to the DirectedWaypoint vector at @p position index.
  /// @param waypoint A DirectedWaypoint to add.
  /// @param position The index in the DirectedWaypoint vector at which
  /// @p waypoint should be added.
  /// @throws std::runtime_error When position is less than 0.
  /// @throws std::runtime_error When position is greater than the size of the
  /// DirectedWaypoint vector.
  void AddWaypoint(const DirectedWaypoint& waypoint, int position);

  /// Getter for the width.
  /// @return The width.
  double width() const { return width_; }

  /// Setter for the width.
  /// @param width The absolute span from one lateral extent to the other of the
  /// api::Lane that the Builder will make from this Connection.
  /// @throws std::runtime_error When @p width is less or equal to zero.
  void set_width(double width) {
    DRAKE_THROW_UNLESS(width > 0.0);
    width_ = width;
  }

  /// Getter of inverse_direction.
  /// @return true when this Connection has inverse direction relative to the
  /// base Lane in the RNDF segment to which this Connection belongs, and false
  /// otherwise.
  bool inverse_direction() const { return inverse_direction_; }

  /// Setter of inverse_direction.
  /// @brief inverse_direction The relative direction regarding another
  /// Connection which will be considered as the reference direction for the
  /// RNDF segment.
  void set_inverse_direction(bool inverse_direction) {
    inverse_direction_ = inverse_direction;
  }

 private:
  // Checks if @p waypoints holds at least two valid waypoints.
  // @param waypoints A vector of DirectedWaypoints to check.
  // @throws std::runtime_error When @p waypoints holds less than two valid
  // DirectedWaypoints.
  void CheckWaypoints(const std::vector<DirectedWaypoint>& waypoints) const {
    int valid_dw = 0;
    for (const DirectedWaypoint& wp : waypoints) {
      if (wp.id().Valid()) valid_dw++;
    }
    DRAKE_THROW_UNLESS(valid_dw > 1);
  }

  // The ID.
  std::string id_;
  // A vector that holds the sequence of the DirectedWaypoints.
  std::vector<DirectedWaypoint> waypoints_;
  // The width of the connection.
  double width_{};
  // A boolean that tells if this connection has an inverse direction relative
  // to another connection which is inside the same RNDF segment and that
  // represents the base lane in the segment.
  bool inverse_direction_{false};
};

}  // namespace rndf
}  // namespace maliput
}  // namespace drake
