function param_sets = getDefaultParams(r)
% NOTEST
  param_sets = struct('walking', atlasParams.Walking(r),...
                      'standing', atlasParams.Standing(r),...
                      'position_control', atlasParams.PositionControl(r),...
                      'recovery', atlasParams.Recovery(r),...
                      'manip',atlasParams.Manip(r));
end
