collision_groups_to_keep:
  - heel
  - toe

attachments:
  - frame: r_hand_mount
    urdf: examples/atlas/urdf/robotiq_box.urdf
  - frame: l_hand_mount
    urdf: examples/atlas/urdf/robotiq_box.urdf

