#!/bin/bash

echo "Compiling..."
gcc -m32 -fPIC -g -c -Wall usblink.c -I /opt/NDIoapi/ndlib/include/ -I /usr/include/libusb-1.0 -DPLATFORM_LINUX

echo "Building shared library..."
gcc -m32 -shared -Wl,-soname,usblink.so.1 -o usblink.so.1 usblink.o -loapi -lftd2xx -lusb

#echo "Copying file..."
#cp usblink.so.1 /opt/NDIoapi/ndigital/usblink.so

echo "done."
