#include "drake/math/continuous_lyapunov_equation.h"

#include <stdexcept>
#include <vector>

#include <Eigen/Core>
#include <gtest/gtest.h>

#include "drake/common/eigen_matrix_compare.h"

namespace drake {
namespace math {
namespace {

using Eigen::MatrixXd;

void SolveRealLyapunovEquationAndVerify(const Eigen::Ref<const MatrixXd>& A,
                                        const Eigen::Ref<const MatrixXd>& Q) {
  MatrixXd X{RealContinuousLyapunovEquation(A, Q)};
  // Check that X is symmetric
  EXPECT_TRUE(
      CompareMatrices(X, X.transpose(), 0, MatrixCompareType::absolute));
  // Check that X is the solution to the discrete time ARE.
  EXPECT_TRUE(CompareMatrices(A.transpose() * X + X * A, -Q, 1E-10,
                              MatrixCompareType::absolute));
}

GTEST_TEST(RealContinuousLyapunovEquation, ThrowInvalidSizedMatricesTest) {
  int n{1}, m{2};

  // non-square A
  MatrixXd A1(n, m);
  A1 << 1, 1;
  MatrixXd Q1(m, m);
  Q1 << 1, 1, 1, 1;

  // non-square Q
  MatrixXd A2(m, m);
  A2 << 1, 1, 1, 1;
  MatrixXd Q2(n, m);
  Q2 << 1, 1;

  // not-same sized
  MatrixXd A3(m, m);
  A3 << 1, 1, 1, 1;
  MatrixXd Q3(n, n);
  Q3 << 1;

  std::vector<MatrixXd> As{A1, A2, A3};
  std::vector<MatrixXd> Qs{Q1, Q2, Q3};

  for (int i = 0; i < static_cast<int>(As.size()); ++i) {
    EXPECT_ANY_THROW(RealContinuousLyapunovEquation(As[i], Qs[i]));
  }
}

GTEST_TEST(RealContinuousLyapunovEquation, ThrowNonSymmetricQTest) {
  int n{2};
  MatrixXd A(n, n);
  A << 1, 1, 1, 1;
  MatrixXd Q(n, n);
  Q << 1, 1, 2, 1;
  EXPECT_ANY_THROW(RealContinuousLyapunovEquation(A, Q));
}

GTEST_TEST(RealContinuousLyapunovEquation, ThrowEigenValuesATest) {
  int n{2};
  // complex pair which adds to zero
  MatrixXd A1(n, n);
  A1 << 0, 1, -1, 0;
  // 0 eigenvalue
  MatrixXd A2(n, n);
  A2 << 0, 0, 0, -1;
  MatrixXd Q(n, n);
  Q << 1, 0, 0, 1;

  EXPECT_ANY_THROW(RealContinuousLyapunovEquation(A1, Q));
  EXPECT_ANY_THROW(RealContinuousLyapunovEquation(A2, Q));
}

GTEST_TEST(RealContinuousLyapunovEquation, Solve1by1Test) {
  int n = 1;
  MatrixXd A(n, n);
  A << -1;
  MatrixXd Q(n, n);
  Q << 1;

  SolveRealLyapunovEquationAndVerify(A, Q);
}

GTEST_TEST(RealContinuousLyapunovEquation, Solve2by2Test) {
  // Example1 from https://www.mathworks.com/help/control/ref/lyap.html
  // Note that Matlab solves AX + XA' + Q = 0
  int n = 2;
  MatrixXd A(n, n);
  A << 1, 2, -3, -4;
  MatrixXd Q(n, n);
  Q << 3, 1, 1, 1;
  MatrixXd X(n, n);
  X << 6.1667, -3.8333, -3.8333, 3;

  EXPECT_TRUE(CompareMatrices(RealContinuousLyapunovEquation(A.transpose(), Q),
                              X, 1E-3, MatrixCompareType::absolute));
  SolveRealLyapunovEquationAndVerify(A.transpose(), Q);
}

GTEST_TEST(RealContinuousLyapunovEquation, Solve3by3Test1) {
  int n = 3;
  MatrixXd A(n, n);
  A << -MatrixXd::Identity(n, n);
  MatrixXd Q(n, n);
  Q << MatrixXd::Identity(n, n);

  SolveRealLyapunovEquationAndVerify(A, Q);
}

GTEST_TEST(RealContinuousLyapunovEquation, Solve3by3Test2) {
  // The system has eigenvalues: lambda_1/2  = -0.5000 +/- 0.8660i
  // and lambda_3 = -1. Therefore, there exists a 2-by-2 block on the
  // diagonal.
  // The compared solution is generated by matlab's lyap function.

  int n = 3;
  MatrixXd A(n, n);
  A << 0, 1, 0, -1, -1, 0, 0, 0, -1;
  MatrixXd Q(n, n);
  Q << MatrixXd::Identity(n, n);
  MatrixXd X(n, n);
  X << 1.5, 0.5, 0, 0.5, 1, 0, 0, 0, 0.5;

  EXPECT_TRUE(CompareMatrices(RealContinuousLyapunovEquation(A, Q), X, 1E-10,
                              MatrixCompareType::absolute));
  SolveRealLyapunovEquationAndVerify(A, Q);
}

}  // namespace
}  // namespace math
}  // namespace drake
